### ISSUE TITLE
Error: Unknown font format

### ISSUE THREAD

**Issue by ArseniySushCorp** [diegomura/react-pdf#1954]
**Describe the bug**
Import fonts is broken, when pass the file path.

**To Reproduce**
https://react-pdf.org/repl?example=font-register

**Comment by carlobeltrame** [comment]
This was fixed in #1934, we are just waiting for a new release of react-pdf now.

**Comment by EvHaus** [comment]
Looks like that change shipped, but the example is still broken.

**Comment by paschaldev** [comment]
For Next.JS, this fixed the issue for me.

- Place the fonts in the `public` directory. I put mine in `/public/fonts`.


```ts

import { PropsWithChildren } from "react";

import { Document, Font, Page, StyleSheet, View } from "@react-pdf/renderer";

const defaultFont = "NunitoSans"; // Set the font family name
 // Regular 400 font. The URL should be publicly accessible
const regularFont = `${process.env.NEXT_PUBLIC_APP_URL}/fonts/nunito-sans.woff2`;

Font.register({
  family: defaultFont,
  fonts: [
    {
      src: regularFont,
      fontWeight: 400,
    },
  ],
});

// Reference font
const styles = StyleSheet.create({
  page: {
    fontFamily: defaultFont,
  },
});

const PdfDocument: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <Document>
      <Page style={styles.page}>
        <View>{children}</View>
      </Page>
    </Document>
  );
};

export default PdfDocument;
```

**Comment by Sergey-lang** [comment]
https://github.com/diegomura/react-pdf/issues/2223#issuecomment-1943292145

**Comment by urbanskimichal** [comment]
I also have this problem, but only when rendering in nodejs. 
In my nextjs 15 app (app router) I can register a font (both from a CDN url or a base64 data url) and successfully render a pdf, but rendering in nodejs (nextjs api route) causes the error `Error: Unknown font format`. 
I can render the pdf in nodejs when using a built-in font.
