### ISSUE TITLE
Using custom font causes usePDF instance to indefinitely remain as 'loading'

### ISSUE THREAD

**Issue by NathZ1** [diegomura/react-pdf#2675]
**Describe the bug**
Registering a custom font with Font.register() results in usePDF never generating the PDF as expected. Commenting out the use of the custom font in StyleSheet allows PDF to generate, which leads me to believe it is an issue with how @react-pdf/renderer instantiates custom fonts. There is no error thrown, making it very difficult to diagnose the issue...

**To Reproduce**
This minimal example of index.tsx shows the reproducible error (React 18, Webpack 5 configuration, NOT Create React App):
```
import React from 'react'
import ReactDOM from 'react-dom/client'
import { Document, Page, Text, Font, usePDF, StyleSheet } from '@react-pdf/renderer'
import ArialBold from './arial-bold.ttf'

Font.register({
  family: 'Arial',
  fonts: [
    {
      src: ArialBold,
      fontStyle: 'normal',
      fontWeight: 'bold'
    }
  ]
})

const styles = StyleSheet.create({
  heading: {
    //comment these 2 lines out and it will generate PDF properly
    fontFamily: 'Arial',
    fontWeight: 'bold',

    fontSize: 20,
    color: '#006699'
  }
})

const App = () => {
  const [instance] = usePDF({
    document: (
      <Document title={'Title'} author={'Author'} subject={'Subject'} pageMode="useNone">
        <Page size="A4">
          <Text style={styles.heading}>text1</Text>
          <Text>text2</Text>
          <Text>text3</Text>
        </Page>
      </Document>
    )
  })

  console.log('ArialBold', ArialBold)
  console.log('Font.getRegisteredFonts().', Font.getRegisteredFonts())
  console.log('instance', instance)

  return (
    <a href={instance.url || undefined} download={'filename.pdf'}>
      DOWNLOAD PDF
    </a>
  )
}

const root = ReactDOM.createRoot(document.getElementById('root')!)

root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
```

Output of console.logs shows the path to the font and the font being registered, however the instance.loading remains = true indefinately. I have followed the path to the font and the path is correct

> 14:25:01.850 index.tsx:39 ArialBold /media/arial-bold.ff5427169c7aaacb3946.ttf
> 14:25:01.850 index.tsx:40 Font.getRegisteredFonts(). {Arial: Font}
> 14:25:01.850 index.tsx:41 instance {url: null, blob: null, error: null, loading: true}

**Expected behavior**
PDF is available to download via instance.url

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chromium
- React-pdf version: 3.3.8

**Comment by cw789** [comment]
It seems I'm encountering the same issue.

**Comment by alyywehby** [comment]
I have the same problem!!

**Comment by vipuljbhikadiya** [comment]
face same problem with next.js when using 
`    const blob = await pdf(MyDoc).toBlob()`

I am using diffrent fonts, but facing issue in only one font (Greycliff CF) , other all fonts are working.

**Comment by Linkerbrain** [comment]
I have the same issue. When downloading an example google font from [this list](https://gist.github.com/sadikay/d5457c52e7fb2347077f5b0fe5ba9300) and importing that, it does work (for example with http://fonts.gstatic.com/s/roboto/v16/zN7GBFwfMP4uA6AR0HCoLQ.ttf)

```import fromlink from "../../font/roboto/good.ttf";
Font.register({
    family: 'Roboto2',
    fonts: [
        { src: fromlink, fontWeight: "normal", fontStyle: "normal" },
    ],
});
```
```

                    const exampleDoc = <Document>
                        <Page>
                            <Text style={{ fontFamily: "Roboto2" }}>This is a test</Text>
                        </Page>
                    </Document>

                    const asPdf = pdf(exampleDoc);
                    console.log("asPdf", asPdf) // prints: Object { on: on4(event, listener), container: {…}, toBlob: toBlob2(), toBuffer: toBuffer2(), toString: toString8(), ... }

                    const str = asPdf.toString();
                    console.log("asPdf", str) // prints: <state>: "pending", <state>: "fulfilled", <value>: "%PDF-1.3\n%����\n9 0 obj\n<<\n/Type /Ex

                    const test = asPdf.toBlob().then(result => {
                        console.log(result); // prints: Blob { size: 4431, type: "application/pdf" }
                    }).catch(error => {
                        console.error("Error generating PDF", error);
                    });
```
However when I then open the same file in [FontForge](https://fontforge.org/en-US/), and export it as "bad.ttf" without changing any of the settings, it suddenly Fails:
```
import fromlink from "../../font/roboto/bad.ttf";
Font.register({
    family: 'Roboto2',
    fonts: [
        { src: fromlink, fontWeight: "normal", fontStyle: "normal" },
    ],
});
```
```
                    const exampleDoc = <Document>
                        <Page>
                            <Text style={{ fontFamily: "Roboto2" }}>This is a test</Text>
                        </Page>
                    </Document>

                    const asPdf = pdf(exampleDoc);
                    console.log("asPdf", asPdf) // prints: Object { on: on4(event, listener), container: {…}, toBlob: toBlob2(), toBuffer: toBuffer2(), toString: toString8(), ... }

                    const str = asPdf.toString();
                    console.log("asPdf", str) // prints: <state>: "pending", <state>: "pending"

                    const test = asPdf.toBlob().then(result => {
                        console.log(result); // NEVER prints!
                    }).catch(error => {
                        console.error("Error generating PDF", error); // NEVER prints!
                    });
```

It also seems to fail on any other non google font in my experience. Can it be that it somewhere only accepts fonts that match the checksum of fonts available via google fonts? Is there any other unspecified encoding parameter that determines if it can handle the .ttf file? There really seems to be barely a difference in the files... I am lost

[font files for reference](https://drive.google.com/drive/folders/13lplJsM22zl2IS0FKH92gFp7VKP9_0X1?usp=sharing)

**Comment by brad-telus** [comment]
Hi @Linkerbrain, I can confirm that using Google Fonts resolves my issue as well. Although this is a big annoyance on my side, since I need access to non-Google fonts.

**Comment by Linkerbrain** [comment]
> Hi @Linkerbrain, I can confirm that using Google Fonts resolves my issue as well. Although this is a big annoyance on my side, since my project needs access to non-Google fonts.

For me that is also the case, custom fonts is an essential part of my project so this is a really breaking issue.

To debug, do you know when streaming the result with a google font, if the last chunks/end event include anything about the font? Maybe we could hotfix it by fake appending a standard end chunk after a set amount of time.

**Comment by brad-telus** [comment]
@Linkerbrain I tried this with a `setTimeout(() => resolve(chunks), 10000)`, and when that timeout was hit the resulting PDF did not have any text in it. It was able to render background colours and images, but the text was not present.

**Comment by SouadAli1010** [comment]
same issue as well

**Comment by bcattonsimply** [comment]
This is happening to me as well.

**Comment by thebigbluebox** [comment]
The way we resolved this was by going back to using the system packaged fonts. We had to fully abandon the use of imported fonts for now.

**Comment by NathZ1** [comment]
> The way we resolved this was by going back to using the system packaged fonts. We had to fully abandon the use of imported fonts for now.

Not really an option for a lot of users that have to adhere to style guides... :(

**Comment by cduff** [comment]
I was hit by this too. After some investigation, it seems to have been caused by the underlying [restructure](https://www.npmjs.com/package/restructure) dependency updating from 3.0.0 to 3.0.1.

**Comment by Skywalker13** [comment]
> I was hit by this too. After some investigation, it seems to have been caused by the underlying [restructure](https://www.npmjs.com/package/restructure) dependency updating from 3.0.0 to 3.0.1.

Have you try a downgrade with `overrides` in your base `package.json` for `restructure`?

**Comment by cduff** [comment]
> > I was hit by this too. After some investigation, it seems to have been caused by the underlying [restructure](https://www.npmjs.com/package/restructure) dependency updating from 3.0.0 to 3.0.1.
> 
> Have you tried a downgrade with `overrides` in your base `package.json` for `restructure`?

Yes, worked for me.

**Comment by Skywalker13** [comment]
> > > I was hit by this too. After some investigation, it seems to have been caused by the underlying [restructure](https://www.npmjs.com/package/restructure) dependency updating from 3.0.0 to 3.0.1.
> > 
> > 
> > Have you tried a downgrade with `overrides` in your base `package.json` for `restructure`?
> 
> Yes, worked for me.

Great, I spend hours yesterday to find the broken dependency without success. Thank you!

**Comment by PelosiTech** [comment]
> I was hit by this too. After some investigation, it seems to have been caused by the underlying [restructure](https://www.npmjs.com/package/restructure) dependency updating from 3.0.0 to 3.0.1.

Thank you, this fixed worked. By adding this to the Resolutions/Overrides. These issues have been fixed. 

What was your process to be able to find this? Curious for future issues. Did you look into the lock file, look into fontkit and dependencies and go one by one to see recent upgrades?

**Comment by nikischin** [comment]
I do have the same issue. However, I noticed it's not the `Font.register` which does break my code, but the usage of the font which is registered within the styles. Not sure if it does make a difference but might be a small hint for debugging the issue.

**Comment by cduff** [comment]
> _**What was your process to be able to find this?**_ Curious for future issues. Did you look into the lock file, look into fontkit and dependencies and go one by one to see recent upgrades?

@PelosiTech I noticed it broke from one deployment to the next even though the version of `@react-pdf/renderer` remained the same. From the git commit log I could see `npm update` had been run. I did a diff on `package-lock.json` and compared to the list of dependencies of `@react-pdf/renderer` retrieved using `npm list --all`. There was a single package that featured in both lists - the `restructure` package, updated from 3.0.0 to 3.0.1.

**Comment by NathZ1** [comment]
> I do have the same issue. However, I noticed it's not the `Font.register` which does break my code, but the usage of the font which is registered within the styles. Not sure if it does make a difference but might be a small hint for debugging the issue.

Yes, that's correct. In my example I originally posted, commenting out the use of the custom font in the stylesheet fixes the issue.

At the moment, overriding the restructure package back to 3.0.0 is the correct workaround, as others have noted above.

**Comment by cduff** [comment]
I'm guessing a bug was introduced into [restructure](https://www.npmjs.com/package/restructure) in 3.0.1. Just now I can't see any new issues listed in its repo related to this: https://github.com/foliojs/restructure/issues.

I'm not familiar enough with the internal workings of `react-pdf` and its use of `restructure` to be able to efficiently do this. I wonder if we can get help from a maintainer for this?

@diegomura
FYI @devongovett

**Comment by brad-telus** [comment]
Hi @diegomura, any updates on this issue? can we add a lock file to ensure this doesn't happen again?

**Comment by tirmey** [comment]
Two days fighting this very issue! 
Indeed, overriding "restrucuture" module to use v. 3.0.0 solves it. Thank yall, so much!

**Comment by buster95** [comment]
oh gosh same problem with fonts
I'm using following code with custom fonts
```typescript
const fileBlob = await pdf(<My Doc />).toBlob()
```
using last version of library 3.4.2
but toBlob() function never throw me errors

**Comment by srl295** [comment]
Hi. I'm new to these tools, but I'm trying to create a repro so I can investigate what's happening in restructure.  Can anyone give some pointers on how to get from a simple use here https://github.com/srl295/pdf-app/blob/master/repro.js to the repros listed here? especially if a specific font can be used, thanks

**Comment by srl295** [comment]
**I have a smaller repro** see https://github.com/foliojs/fontkit/issues/331#issuecomment-2040790107

**Comment by Frontend-io** [comment]
> > I was hit by this too. After some investigation, it seems to have been caused by the underlying [restructure](https://www.npmjs.com/package/restructure) dependency updating from 3.0.0 to 3.0.1.
> 
> @cduff Appreciate you posting this. Thank you, this fixed worked. By adding this to the Resolutions/Overrides. These issues have been fixed.
> 
> NPM package.json ` "overrides": { "restructure": "3.0.0" }` or Yarn/PNPM package.json ` "resolutions": { "restructure": "3.0.0" }`
> 
> _**What was your process to be able to find this?**_ Curious for future issues. Did you look into the lock file, look into fontkit and dependencies and go one by one to see recent upgrades?

Thanks man, you made my day! Been debugging this issue for the past two nights!

**Comment by srl295** [comment]
@Frontend-io I have a merged PR in the dep's dep that fixes it. Just waiting for @devongovett to make a new restructure release to patch.

**Comment by ashkankiani** [comment]
I have the same problem also.

**Comment by sergical** [comment]
> I was hit by this too. After some investigation, it seems to have been caused by the underlying [restructure](https://www.npmjs.com/package/restructure) dependency updating from 3.0.0 to 3.0.1.

You saved my life

**Comment by srl295** [comment]
I'm still waiting on restructure to publish a 3.0.2 with the actual fix. It's already merged.

**Comment by karlhorky** [comment]
> @cduff Appreciate you posting this. Thank you, this fixed worked. By adding this to the Resolutions/Overrides. These issues have been fixed.
> 
> NPM package.json ` "overrides": { "restructure": "3.0.0" }` or Yarn/PNPM package.json ` "resolutions": { "restructure": "3.0.0" }`

@PelosiTech thanks for the workaround!

You could also update your post for those using [pnpm Overrides](https://pnpm.io/package_json#pnpmoverrides):

```json
{
  "pnpm": {
    "overrides": {
      "restructure": "3.0.0"
    }
  }
}
```

**Comment by karlhorky** [comment]
Devon released [`restructure@3.0.2`](https://github.com/foliojs/restructure/releases/tag/v3.0.2) with [the fix](https://github.com/diegomura/react-pdf/issues/2675#issuecomment-2040796585) from @srl295, which I can confirm fixes the issue with custom fonts for us.

@NathZ1 if this also resolved for you, I guess the issue can be closed?

**Comment by muhammadkasimm** [comment]
In my NextJS (App Router) app, I finally resolved this by:

### 1. Adding my local fonts to `/public/fonts/` directory.
<img width="355" alt="image" src="https://github.com/user-attachments/assets/b87ad348-147e-42ee-a453-4f0f987e9978">


### 2. Defining font-faces in a `fonts.css` file
**IMPORTANT:** Only use numeric weights. Kept running into issues until I used numeric weights when defining font-faces, registering font and using fonts in the document.

<img width="572" alt="image" src="https://github.com/user-attachments/assets/6082ff5c-1614-442b-b2a4-956a1cecc6ab">


### 3. Importing `fonts.css` in app's `global.css`
<img width="458" alt="image" src="https://github.com/user-attachments/assets/ca815df3-f5ae-4504-87c0-897f1c3fb7f0">


### 4. Registering font using only numeric weights
<img width="394" alt="image" src="https://github.com/user-attachments/assets/bc1e5e50-2c4f-4520-8ae4-44e519350968">

### 5. Using font with numeric font weights
<img width="415" alt="image" src="https://github.com/user-attachments/assets/1ddaf8c8-3b39-47d2-a92f-26fdde1ff4c7">



Before I switched to using numeric weights throughout, I was able to render the correct fonts and weights while previewing document but as soon as I tried downloading using `pdf(myDocument).toBlob()`, it would fail saying: `Could not resolve font for EBGaramond, fontWeight 400`.

**Comment by srl295** [comment]
@muhammadkasimm hey, I'm glad you got it working for you.  However, you might be encountering a different issue, as the issue here had to do with a bug I introduced (sorry!) but was fixed in `restructure@3.0.2` . can you do `npm ls -a` and see what version of restructure you saw ?

more generally, should this issue be closed or fixed in react-pdf?

**Comment by KKKircheff** [comment]
I have problem adding custom fonts to react-pdf/renderer in app (nextjs 15 and React 19) and there is no work arround. Font.register registers the fonts correctly, but the problem is in Font.load function. When called to load a registered font it returns "value is undefined". I am using lates versions of all packages. ( Restructure back to 3.0.0 does not work and they said the bug is fixed in 3.0.2).

**Comment by oceanlvr** [comment]
@KKKircheff  same issue have you fixed?

**Comment by karlhorky** [comment]
@diegomura since [`restructure@3.0.2`](https://github.com/foliojs/restructure/releases/tag/v3.0.2) has been [released with the fix in June 2024](https://github.com/diegomura/react-pdf/issues/2675#issuecomment-2171686473), do you think that this issue should be closed now?

**Comment by oceanlvr** [comment]
issue fixed

**Comment by KKKircheff** [comment]
fixed

**Comment by AstralBaby** [comment]
I'm still unable to make it work with inter. it is loading indefinetely.

**Comment by KKKircheff** [comment]
Here is how i use fonts in one of my components in my Nextjs 15 app:

    Font.register({
        family: 'Inter',
        fonts: [
             { src: `${originURL}/fonts/Inter/Inter-Light.ttf`, fontWeight: 'light' },
            { src: `${originURL}/fonts/Inter/Inter-Regular.ttf`, fontWeight: 'normal' },
            { src: `${originURL}/fonts/Inter/Inter-Medium.ttf`, fontWeight: 'medium' },
            { src: `${originURL}/fonts/Inter/Inter-Bold.ttf`, fontWeight: 'bold' },
        ],
    });

    Font.register({
        family: 'Montserrat',
        fonts: [
            { src: `${originURL}/fonts/Montserrat/Montserrat-Medium.ttf`, fontWeight: 'medium' },
            { src: `${originURL}/fonts/Montserrat/Montserrat-Bold.ttf`, fontWeight: 'bold' },
        ],
    });

    Font.registerHyphenationCallback((word: string) => [word]);

So important rules : 
 - place all fonts in 'public' and then 'fonts' folder for example ( you can separate them in sub folders if you like).
 -  load them dynamically from localhost or your domain  domain name (  for me originURL = process.env.NEXT_PUBLIC_APP_ADDRESS;) 
 - Be sure that you have all fonts you load in public/fonts folder and names are written WITHOUT ANY TYPOS 

And it should work
