### ISSUE TITLE
Cannot use with Japanese? ("Cannot read property 'layout' of null")

### ISSUE THREAD

**Issue by SachaG** [diegomura/react-pdf#270]
This seems like a strange issue but I'm able to render a PDF in-browser fine when it's using English characters, but as soon as I switch for Japanese characters (`一時使用目的の建物賃貸借契約書`) I get the following error:

```
 TypeError: Cannot read property 'layout' of null
```

You can reproduce the error here by replacing any text with that Japanese string: http://react-pdf.diegomura.com/repl

**Comment by SachaG** [comment]
Btw I can confirm the issue also happens on the server when using the method described in #269.

**Comment by SachaG** [comment]
Oh could this just be because I haven't added the proper Japanese font?

**Comment by diegomura** [comment]
It could. Please try loading an appropriate font and sharing your comments here. Didn't have time to test with non-latin languages yet, but it's definitely something we should support

**Comment by SachaG** [comment]
After adding the font (otf), I get a different error:

```
Error occurred while rendering: "TypeError: Cannot read property 'hasGlyphForCodePoint' of null"
```

**Comment by SachaG** [comment]
I also get:

```
Error occurred while rendering: "Error: Unknown font format"
```

**Comment by SachaG** [comment]
Sorry for the multiple messages, but I think I'm also having some issues actually loading the font files. After loading a remote file using a URL (local files seem to not be found) I'm back to `"TypeError: Cannot read property 'layout' of null"` :(

**Comment by SachaG** [comment]
This is driving me crazy… as far as I can tell I didn't change anything, yet I'm not getting the same error anymore. On the other hand the characters are all jumbled up: 

![https://d3vv6lp55qjaqc.cloudfront.net/items/18221K3k1E3O0S1o2E1G/Screen%20Shot%202018-08-02%20at%2010.57.36.png?X-CloudApp-Visitor-Id=43642&v=1fb7fef9](https://d3vv6lp55qjaqc.cloudfront.net/items/18221K3k1E3O0S1o2E1G/Screen%20Shot%202018-08-02%20at%2010.57.36.png?X-CloudApp-Visitor-Id=43642&v=1fb7fef9)

**Comment by SachaG** [comment]
So apparently different characters result in different behaviors. `一時使用目的の建物賃貸借契約書` triggers the error, while `先日送ってもらった住民票なんだけど` results in the jumbled text…

**Comment by SachaG** [comment]
It gets weirder. You can try on http://react-pdf.diegomura.com/repl

- Paste in `一時使用目的の`: no error. 
- Paste in `建物賃貸借契約書`: no error.
- Paste in `一時使用目的の建物賃貸借契約書` (so both together): layout error. 

So it seems to be somehow related to the number of different characters? Is that possible?

**Comment by diegomura** [comment]
I don't think it makes much sense to be related with the number of characters, but it can cause a side effect I'm not being able to see clear now. 
Thanks for testing the library! I'll give priority to this and try to work soon on supporting Japanese characters

**Comment by diegomura** [comment]
OTF is supported. Would be great if you can provide a anippet I can then test to see what's going on. However, these two issues seem unrelated

**Comment by diegomura** [comment]
@SachaG @farmstrong8 Japanese fonts are fixed on newest version. You can see a live example [here](http://react-pdf.diegomura.com/repl?code=1887b07602e07404e0a6073025819c271802800600b084003805c03d2900900de03b926002620d50036200c6021844b852e106802fa90066e020a5201ace120990a0131d800d00022a1ac5700b6495804f621a0390069798a2198dc2025006e00502e3b8341ad11d670506802f068032842f9c086e1c1c34073c0f1c26150b8686ba000784298a5a5a4d885200179c298013002b1aaa5e4db03ea189b99582a4998d708ba3abbba784068020a1211046a60390401f18cd400f0008a7002b9e9c2424cd5a6cc00297021c37b15c20401100c00b09c6de5e6cc00a9c1677b85fa0550f9f8a32a3c430a4e0001ca0084cd00fef2800a57401ddba0042dd00760c802fbd402593a018663001d31807c054022a6a00417d001f66b35203cb2d71b869ee3f67844de1f7f37cb27f20582a170a45a2b1b8fc4fc89375253ca99497b5332bf49a00251500a7a6804004c03183200cc1900410c80488649601f41900f2f280441b4005a7a00ac1900c90c8003064022832012c18f104882736e66f26bddefcafa0ae920884c34d1ccda5ac9bcdb445ed3f3f82251189c6bb09eead95abd54df6d2014ec640659c1f6686b9a45dbec8978c5870566b734b81c6e00129c0b81c0836de6c0581ac18184c2cc86235224d9c4000)

This is using a `ttf` font to render these types of chars. From what I get from you, `otf` files were giving you trouble. I'm going to create a separate issue to do some more extensive testing on that format. 

Thanks for testing the lib!

**Comment by GWStuartClift** [comment]
It looks like this is still an issue using your [example](https://react-pdf.org/repl?code=1887b07602e07404e0a6073025819c271802800607a5c02403780ee4980098825400d880318086112e1400588680beb9a2c9035c00cdc0414b80359c24632140810476003400088802875ea45300b6496804f005cea011006959f2225ad3c025006e2d5a1b834ead09da7028ea00bcea00ca10fe70611c7070d00cf02c7098dabae8001e101669ba7ae26148005e7016004c00acaa3a79f6c086c6e656b672e28eba3c4e6e1e5e603e0082000e8321ea98ce21007c6335003c00228c00ae0670909335bab3000a4c0870bec570c196fd002c961b7979b3002a7059be9101c1447e01288a0f103c93800072802133403fbca00295d00776e8010b7401d83200bef500964e806198c0074c601f015008a9a80105f4007d9acd70f72c95daeea3bb7c9e5157bbd025f2cafd01a0c86c311a8cc4e2f1df4275c498f4a4539e54cc8fd268009454029e9a01001300c60c803306401043201221825807d06403cbca01106d00169e802b064032432000c19008a0c804b065c7e2201c9ba9ac92f379f33e02da703c1d0937b33616d24f26d513b77d7ef0e47a3b12e825bab696cf6527d34ffa3a19fee6506d921ce6e176fb426e3160c159accd5a6e968004a702603020db79b01606b0a06130b32188d70936e900).

**Comment by redcranesolutions** [comment]
We are also having the same issue with Japanese fonts.

**Comment by skjo0c** [comment]
I have an Otf file of `Proxima-Nova-Regular`. When I tried to import like following:

```
Font.register({
  family: 'ProximaNova',
  src: '../../assets/fonts/Proxima-Nova-Regular.otf',
})
```

I get error of `Unknown font format`

**Comment by diegomura** [comment]
Otf files are not supported. Obly ttf
