### ISSUE TITLE
Nested text styling does not work on Windows

### ISSUE THREAD

**Issue by RKukharchuk** [diegomura/react-pdf#2725]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

Rendering this document with Roboto is messing up the formatting of next next blocks:
```
 <Document>
      <Page size="LETTER" wrap>
        <Text>
          <Text style={{ fontFamily: "Roboto", fontWeight: 'bold' }}>
            Should be bold
          </Text>
          <Text> Shouldn't be bold</Text>
        </Text>
      </Page>
    </Document>
```
Produces the following result
![image](https://github.com/diegomura/react-pdf/assets/31829779/035b4eb2-9443-449b-a862-042b945d158d)

Making the second part bold is doing nothing:
```
 <Document>
      <Page size="LETTER" wrap>
        <Text>
          <Text>
            Shouldn't be bold
          </Text>
          <Text style={{ fontFamily: "Roboto", fontWeight: 'bold' }}> Should be bold</Text>
        </Text>
      </Page>
    </Document>
```
Produces the following result:
![image](https://github.com/diegomura/react-pdf/assets/31829779/5804db18-6d26-47e6-8ea7-acc752751e4e)

**Expected behavior**
Text formatted according to the fontWeight.

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- React-pdf version 3.4.3
-

PS: It works perfectly on MacOS

**Comment by RKukharchuk** [comment]
After future inverstigations it looks like it's related to fonts resolution of text.
Downgrading @react-pdf/layout to 3.11.5 helps to resolve the issue

**Comment by Fry98** [comment]
@RKukharchuk Are you on Intel or Apple Silicon Mac? I'm on Macbook Air M3 and have still encountered this issue.

**Comment by focux** [comment]
I'm on Apple Silicon and I'm also having this issue, downgrading `@react-pdf/layout` made it work for me.

If anyone is wondering about how to do it, this how you do it with PNPM, update your package.json to resolve the layout version that we want:

```
"pnpm": {
    "overrides": {
      "@react-pdf/layout": "3.11.5"
    }
  },
```

**Comment by vincentanu04** [comment]
Can someone help me with this? I am a beginner, thanks in advance!

This is my code: 
```

const styles = StyleSheet.create({
  boldText: {
    fontWeight: 700,
  },
  normalText: {
    fontWeight: 400,
  },
});

<Text style={{ display: 'flex', width: '100%' }}>
      <Text style={styles.boldText}>{title}</Text>
      <Text>:{'  '}</Text>
      <Text style={styles.normalText}>{data}</Text>
</Text>
```

I have downgrade react-pdf/renderer to a version (3.4.2) which uses react-pdf/layout version 3.11.5. However, this issue still persists.
Below is my package.json:

{
  "name": "cv-builder",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "lint": "eslint . --ext js,jsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "@react-pdf/renderer": "^3.4.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.37",
    "@types/react-dom": "^18.2.15",
    "@vitejs/plugin-react": "^4.2.0",
    "eslint": "^8.53.0",
    "eslint-plugin-react": "^7.33.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.4",
    "npm-force-resolutions": "^0.0.10",
    "vite": "^5.0.0"
  },
  "resolutions": {
    "@react-pdf/layout": "3.11.5"
  }
}

**Comment by ipranay** [comment]
Doesn't seem to work for me, even with the downgrade to `"@react-pdf/layout": "3.11.5"`.

Do we also need to downgrade the "@react-pdf/renderer" version?
I'm at 3.4.4

**Comment by ipranay** [comment]
> Doesn't seem to work for me, even with the downgrade to `"@react-pdf/layout": "3.11.5"`.
> 
> Do we also need to downgrade the "@react-pdf/renderer" version? I'm at 3.4.4

Answering my own question, going back to `"@react-pdf/renderer": "3.4.2"` seems to work.

**Comment by life-engineered** [comment]
I'm on MacOS and downgrading to "@react-pdf/renderer": "3.4.2" did not work

**Comment by landlessfarm** [comment]
I'm using yarn.

Uninstalling everything, 
reinstalling renderer, 
installing layout 3.11.5,
adding "resolutions: {@react-pdf/layout@3.11.5}",
and finally dropping down to 3.4.2  for renderer

Did in fact work for me (for production as well).

**Comment by crohn** [comment]
The font selection has been fixed in `@react-pdf/layout@3.13.0` (see [Changelog](https://github.com/diegomura/react-pdf/blob/master/packages/layout/CHANGELOG.md#3130)), which has been included in `@react-pdf/renderer@3.4.5` (see [Changelog](https://github.com/diegomura/react-pdf/blob/master/packages/renderer/CHANGELOG.md#345).

So basically if you update `@react-pdf/renderer` to version `3.4.5` the issue should be solved, or at least this was my case.

**Comment by alex-boehm** [comment]
Updating @react-pdf/renderer to version 3.4.5 solved the issue for us :)

**Comment by Vanals** [comment]
Hello people I am still having the issue even tho I am using react-pdf/renderer 3.4.5

`Error parsing style attribute "font-family: GT-Walsheim" for tag: P TypeError: cssParse is not a function`
