### ISSUE TITLE
Copy and pasting Roboto font from Chrome PDF preview results in missing characters.

### ISSUE THREAD

**Issue by pd2xts** [diegomura/react-pdf#2762]
**Describe the bug**

Using Google's Roboto TTF fonts, when I copy and past from Chrome PDF preview, certain characters in my pasted text are missing. For example the copied word **beneficial**, pastes as **benefcial**, missing an i.

This seems very similar to this now-resolved issue https://github.com/diegomura/react-pdf/issues/1950.

**To Reproduce**

Version `"@react-pdf/renderer": "^3.4.4"`

Font registration:

```tsx
Font.register({
    family: 'Roboto',
    fonts: [
      {
        src: '/fonts/Roboto-Regular.ttf'
      },
      {
        src: '/fonts/Roboto-Light.ttf',
        fontWeight: 200
      },
      {
        src: '/fonts/Roboto-Italic.ttf',
        fontStyle: 'italic'
      },
      {
        src: '/fonts/Roboto-Bold.ttf',
        fontWeight: 600
      },
      {
        src: '/fonts/Roboto-BoldItalic.ttf',
        fontStyle: 'italic',
        fontWeight: 600,
      },
    ],
  })
```

- Open PDF document in Google Chrome PDF preview
- Copy and paste text
- Characters are missing in pasted text

If I download the document and do the same thing using Mac OS Preview, then the characters copy and paste correctly.

**Expected behaviour**

Characters copy and paste correctly

**Desktop:**

- OS: MacOS 12.7.5 
- Browser Chrome 125.0.6422.77
- React-pdf version 3.4.4

**Comment by AbdelMounhim** [comment]
it seems like [fix: copy-paste for registered font](https://github.com/diegomura/react-pdf/pull/2488)

**Comment by AbdelMounhim** [comment]
I have the same problem, using Roboto web fonts

```
Font.register({
  family: 'Roboto',
  src: 'https://fonts.gstatic.com/s/roboto/v19/KFOmCnqEu92Fr1Mu4mxPKTU1Kg.ttf',
});

Font.register({
  family: 'Roboto-Bold',
  src: 'http://fonts.gstatic.com/s/roboto/v15/d-6IYplOFocCacKzxwXSOKCWcynf_cDxXwCLxiixG1c.ttf',
});
```

**Comment by diegomura** [comment]
This should be fixed in latest versions

**Comment by pd2xts** [comment]
@diegomura which version specifically fixes this? I'm at 4.1.4 and still seeing the problem.

**Comment by AbdelMounhim** [comment]
workaround that was working for me : use another font

```
Font.register({
  family: 'Raleway',
  src: 'http://fonts.gstatic.com/s/raleway/v12/1Ptug8zYS_SKggPNyC0ISg.ttf',
});
Font.register({
  family: 'Raleway-Bold',
  src: 'http://fonts.gstatic.com/s/raleway/v12/1Ptrg8zYS_SKggPNwJYtWqZPBQ.ttf',
});
```
