### ISSUE TITLE
"Cannot enlarge memory arrays" when Page components is used with wrap prop

### ISSUE THREAD

**Issue by rsolci** [diegomura/react-pdf#295]
First of all, awesome work!

**OS:** Ubuntu Linux 16.04

**React-pdf version:** 1.0.0-alpha.15

**Description:** When rendering a small pdf on client-side it renders ok. If i try to add `wrap` prop on my `Page`component, the pdf didn't render and i got this message on dev console: 
`Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 134217728, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 `

**How to replicate issue including code snippet (if applies):**

Component file: 
```
class Profile extends Component {
  render () {
    return (
      <div>
        <Document style={{height: '500px', width: '100%'}}>
          <Page size="A4" style={styles.page} wrap>
            <View style={styles.header} fixed>
              <Image src='/logo.png' />
            </View>
            <View>
              <Text style={styles.mainTitle} >Profile</Text>
              <Text style={styles.titleDetail}>{new Date().toLocaleDateString('pt-BR', {day: 'numeric', month: 'long', year: 'numeric'})}</Text>
            </View>
            <View style={styles.section}>
              <Text>Section #1</Text>
            </View>
            <View style={styles.section}>
              <Text>Section #2</Text>
            </View>
          </Page>
        </Document>
      </div>
    )
  }
}
```

App.js
```
import { Profile } from 'some-path'

...

<Route path="/mypdf" exact={true} component={Profile} />

```

**Comment by diegomura** [comment]
Thanks! I’m going to need the styles you defined for that document in order to replicate it

**Comment by rsolci** [comment]
In order to isolate the cause of the problem, i created a new project using create-react-app
Here are the files:

```Profile.js
import React, { Component } from 'react'
import { Page, Text, View, Document, StyleSheet, Image } from '@react-pdf/renderer';

// Create styles
const styles = StyleSheet.create({
  page: {
    backgroundColor: '#FFF',
    padding: 20
  },
  section: {
    margin: 10,
    padding: 10,
    flexGrow: 1
  },
  header: {
    height: 44,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  mainTitle: {
    color: '#0095d9',
    textAlign: 'center',
    fontFamily: 'Helvetica-Bold',
    marginTop: 20,
  },
  titleDetail: {
    fontSize: 10,
    textAlign: 'center',
    marginTop: -5,
  }
});

class Profile extends Component {
  render () {
    return (
      <Document style={{height: '500px', width: '100%'}}>
        <Page size="A4" style={styles.page}>
          <View style={styles.header} fixed>
          </View>
          <View>
            <Text style={styles.mainTitle} >Profile</Text>
            <Text style={styles.titleDetail}>{new Date().toLocaleDateString('pt-BR', {day: 'numeric', month: 'long', year: 'numeric'})}</Text>
          </View>
          <View style={styles.section}>
            <Text>Section #1</Text>
          </View>
          <View style={styles.section}>
            <Text>Section #2</Text>
          </View>
        </Page>
      </Document>
    )
  }
}

export default Profile
```

```App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

import Profile from './Profile'

class App extends Component {
  render() {
    return (
      <div className="App">
        <Profile />
      </div>
    );
  }
}

export default App;
```

``` index.js
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';

ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
```

**Comment by rsolci** [comment]
Weird behaviour:
When i commented out the `flexGrow: 1` from styles.section it worked.
Knowing this, i went back to my main project, and it's now working, even with the style. But for safe measure, i removed the style.

I'll keep designing my pdf and if i encouter this problem again, i'll update this issue

**Comment by diegomura** [comment]
should be fixed with new `1.0.0-alpha.16` version. Please ping if didnt

**Comment by binchik** [comment]
@diegomura Hey, thanks for your awesome @react-pdf project. It's helping me a log.

I get the "Cannot enlarge memory arrays" error when pdf is big. It renders about 450 pages fine on my machine. But if I try to generate a pdf with more pages it gets stuck and finally results in "Cannot enlarge memory arrays" error. Is it solvable?

**Comment by sanohin** [comment]
@diegomura  Well, it still doesn't work with bigger files. And in my case there are no styles.
```javascript
const dummyText = "Casi todo aquel día caminó sin acontecerle cosa que de contar fuese, delo cual se desesperaba, ";
const moreText = dummyText.repeat(100);

const App = () => (
  <Document>
    <Page>
      <Text>{moreText}</Text>
    </Page>
  </Document>
)
```

**Comment by ishraqiyun77** [comment]
I'm running into the same issue. The work around I'm currently using because I can't think of a better way, is to modify `node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js`. Around line 460 there is the integer `134217728`. I'm increasing it and it resolves the issue. 

Not the best solution, and definitely not permanent since it will just get erased when the package is updated. It at least resolves the issue. I'm open to a more permanent solution.

**Comment by diegomura** [comment]
Thanks @sanohin and @ishraqiyun77 .
You're right. This is a yoga issue and I don't know if there's anything on my end I can do to fix it.
I'm currently working on a improved text-layout solution, and I hope this get's fixed there, since we prevent to layout big chunks of text when it's not needed. It's not an easy task, so I'm not sure when it's going to be finished, but I have made a lot of progress so far.
I'll keep you posted!

**Comment by naomiajacobs** [comment]
@diegomura I'm also running into this - checking to see if there's an update on when a fix for this would be released. Thanks for the help!

**Comment by mcronline** [comment]
> I'm running into the same issue. The work around I'm currently using because I can't think of a better way, is to modify `node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js`. Around line 460 there is the integer `134217728`. I'm increasing it and it gets around the issue.
> 
> Not the best solution, and definitely not permanent since it will just get erased when the package is updated. It at least is a work around the issue although it generates a warning about the heap size.
> 
> I'm open to a more permanent solution.

I change and save the file as you said, but seens it doesn't change when running the app. What I'm missing?

**Comment by krishankantray** [comment]
this issue still exits, I am using v2.0.0-beta.6
is there any solution to this yet ??

**Comment by jaesharma** [comment]
@krishankantray I was facing the same issue, just resolved it. This is caused by the wrong CSS, which could be anything. You need to find out by yourself in your code. For me it was "width property", I was setting it 99vw on the parent component and again 100vw on the child. Someone at the top mentioned it was "wrap" property for them, so I assume you need to debug your CSS code to resolve it.

**Comment by vmontanheiro** [comment]
Closed ?? hahah

Unhandled Rejection (Error): abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 134217728,

`import React from 'react';
import { Page, Text, View, Document, StyleSheet, Font, PDFViewer } from '@react-pdf/renderer';
import RobotoBold from './Roboto-Bold.ttf';
import RobotoRegular from './Roboto-Regular.ttf';

Font.register({
  family: `Roboto`,
  fonts: [
    { src: RobotoRegular },
    {
      src: RobotoBold,
      fontWeight: 600,
    },
  ],
});

const styles = StyleSheet.create({
  page: {
    width: `100%`,
    height: `100%`,
  },
});

const operators = Array(50).fill(`OPERATOR NAME`);

const MyDocument = () => (
  <PDFViewer width="100%" height="100%">
    <Document>
      <Page size="A4" style={styles.page} wrap>
        <View wrap={false}>
          {operators.map((operator, index) => (
            <Text>{`${operator} ${index}`} </Text>
          ))}
        </View>
      </Page>
    </Document>
  </PDFViewer>
);

export default MyDocument;
`

We lost a lot of time with this lib, it cannot render 50 items dynamically and you guys closed all the problems related to that. Hahaha it is very easy to keep a lib with your ass.

**Comment by gabrielvincent** [comment]
> Closed ?? hahah
> 
> ```
> Unhandled Rejection (Error): abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 134217728,
> 
> import React from 'react';
> import { Page, Text, View, Document, StyleSheet, Font, PDFViewer } from '@react-pdf/renderer';
> import RobotoBold from './Roboto-Bold.ttf';
> import RobotoRegular from './Roboto-Regular.ttf';
> 
> Font.register({
>   family: `Roboto`,
>   fonts: [
>     { src: RobotoRegular },
>     {
>       src: RobotoBold,
>       fontWeight: 600,
>     },
>   ],
> });
> 
> const styles = StyleSheet.create({
>   page: {
>     width: `100%`,
>     height: `100%`,
>   },
> });
> 
> const operators = Array(50).fill(`OPERATOR NAME`);
> 
> const MyDocument = () => (
>   <PDFViewer width="100%" height="100%">
>     <Document>
>       <Page size="A4" style={styles.page} wrap>
>         <View wrap={false}>
>           {operators.map((operator, index) => (
>             <Text>{`${operator} ${index}`} </Text>
>           ))}
>         </View>
>       </Page>
>     </Document>
>   </PDFViewer>
> );
> 
> export default MyDocument;
> ```
> 
> We lost a lot of time with this lib, it cannot render 50 items dynamically and you guys closed all the problems related to that. Hahaha it is very easy to keep a lib with your ass.

Wow. This is an incredibly rude and childish comment. I’ve been using this lib for 6 months and have already generated PDF files with more than 950 pages, rendering thousands of dynamic items. 

Thankfully the open source community has people that are nothing like you. The work Diego Mura and others have put into this project is incredible.

If you believe this issue has not yet been fully fixed, you’re more than welcome to open an issue or even a pull request.

I pitty the people who have to work with you.

**Comment by diegomura** [comment]
Thank you @gabrielvincent . I appreciate your words. Unfortunately it is what we have to deal once in awhile

**Comment by Skywalker13** [comment]
Try https://github.com/diegomura/react-pdf/issues/1063#issuecomment-749087846
