### ISSUE TITLE
@react-pdf/types@2.8.0 not working at all!

### ISSUE THREAD

**Issue by jgo80** [diegomura/react-pdf#3088]
**Describe the bug**
Unfortunately all kind of types are not working anymore.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

```
import { BulkLoad } from '@react-pdf/types'; // Module '"@react-pdf/types"' has no exported member 'BulkLoad'
import { Font } from '@react-pdf/renderer'; // exports const Font: FontStore

Font.register({}) // method Font.register refers to "any"
```

_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_

**Expected behavior**
Make the types work again

**Screenshots**

**Desktop (please complete the following information):**

- React-pdf version 9.2.1
- @react-pdf/types@2.8.0

**Comment by airjp73** [comment]
It looks like this is fixed in the code via [this commit](https://github.com/diegomura/react-pdf/commit/7cd66e4fc37cd1393adc6250a919fe2629812082), so theoretically we just need a release with that fix.

**Comment by diegomura** [comment]
Should be fixed. Please re open if more issues appear

**Comment by EvHaus** [comment]
The latest versions:

- @react-pdf/renderer@4.2.3
- @react-pdf/types@2.8.1

still throw this error for me:

```
file.tsx:36:6 - error TS2339: Property 'register' does not exist on type 'typeof FontStore'.

36 Font.register({
```

**Comment by karlhorky** [comment]
@EvHaus it appears that new versions have been released:

- [`@react-pdf/renderer@4.2.4`](https://github.com/diegomura/react-pdf/releases/tag/%40react-pdf%2Frenderer%404.2.4)
- [`@react-pdf/types@2.8.2`](https://github.com/diegomura/react-pdf/releases/tag/%40react-pdf%2Ftypes%402.8.2)

Do these versions work for your use case?

**Comment by EvHaus** [comment]
Yes. Fixed in latest

**Comment by jgo80** [comment]
Unfortunately I have to disagree! In the latest version `BulkLoad` still is not exported in `@react-pdf/types/font.d.ts`, it has to be added to the export.

**Comment by karlhorky** [comment]
@jgo80 are you sure that you updated all versions of your packages to the latest versions? (also check lockfiles)

I can confirm that on our side the types are also working with the latest versions.

**Comment by jgo80** [comment]
@karlhorky yes i am sure, see yourself in the code of the repo: packages/types/font.d.ts

**Comment by jgo80** [comment]
@karlhorky I'm not quite sure if you're serious or if you're trying to make fun of me 😕 My code is already present in the initial post, this was the reason to open this issue.

> 
> **To Reproduce** Steps to reproduce the behavior including code snippet (if applies):
> 
> ```
> import { BulkLoad } from '@react-pdf/types'; // Module '"@react-pdf/types"' has no exported member 'BulkLoad'
> ```

Did you even take a look at [font.d.ts](https://github.com/diegomura/react-pdf/blob/master/packages/types/font.d.ts)? 
It is just missing the `BulkLoad` export.

so instead of 

```
export {
  FontStyle,
  FontWeight,
  EmojiSource,
  FontDescriptor,
  HyphenationCallback,
  FontStoreType as FontStore,
} from '@react-pdf/font';
```

it has to be

export {
  FontStyle,
  FontWeight,
  EmojiSource,
  FontDescriptor,
  HyphenationCallback,
  FontStoreType as FontStore,
  Bulkload
} from '@react-pdf/font';
```

**Comment by karlhorky** [comment]
@jgo80 sorry, missed that you opened the issue.

**Comment by jgo80** [comment]
@diegomura maybe you could consider this for the next release. Thx!
