### ISSUE TITLE
React-pdf 1.2.1 not working on codesandbox.io

### ISSUE THREAD

**Issue by modemmute** [diegomura/react-pdf#462]
When testing for some bugs I'm experiencing I tried react-pdf on codesandbox.io.

As soon as you import any part of @react-pdf/renderer to the page you get the following error:
"Potential infinite loop: exceeded 10001 iterations."

https://codesandbox.io/s/308l7yox21

**Comment by diegomura** [comment]
Yes. I'm aware of this. I think this was introduced when we switch from `yoga-layout` to `yoga-layout-prebuilt`, but not sure. This is not something specific to 1.2.1 either.

The error is very cryptic and I would love the lib to work on codesandbox, but I didn't have time yet to take a look at what's going on here. The best way to identify what's going on would be knowing between which versions this got broken, and then seeing the diff of those versions.

Keeping this open for further research

**Comment by diegomura** [comment]
In the meantime, disabling `Infinite Loop Protection` in the `sandbox.config.json` file makes this error go away. However, the blob does not get rendered inside the iframe, which is weird. IF you open the blob in another tab you can see the pdf document just fine. Also this seems to be just a Chrome issue. I tried it on Firefox and everything is OK.

<img width="1179" alt="screen shot 2019-01-24 at 3 52 14 pm" src="https://user-images.githubusercontent.com/5600341/51701358-0e0f3300-1ff0-11e9-90f8-306490fe2652.png">

**Comment by DuncanMacWeb** [comment]
We have also been experiencing this error in Firefox. In Firefox, when you accept the prompt to stop a long-running script...
<img width="578" alt="A web page is slowing down your browser. What would you like to do? (button) Stop it. (button) Wait." src="https://user-images.githubusercontent.com/593122/52273844-eb134600-2942-11e9-98e4-4c3b321a1e2e.png">
... it produces a long stack trace that appears to be linked to yoga-layout(-prebuilt). Sorry about the horrendous length! Let me know if a stack trace from source maps would be useful (I didn’t work out how to get it but can dig in some more).

This may be related to / the cause of the bug in IE (#413), but I haven’t been able to extract a stack trace in IE yet.

| With `yoga-layout-prebuilt`: | With `yoga-layout`: |
|------------------------------|---------------------|
| `Error: Script terminated by timeout at:`<br>`positionAtIndex@bundle.js:35264:21`<br>`getGlyphWidth@bundle.js:35278:12`<br>`finalizeLineFragment/<@bundle.js:34277:28`<br>`layoutParagraph/</<@bundle.js:34345:7`<br>`layoutParagraph/<@bundle.js:34344:5`<br>`layoutContainer@bundle.js:34362:23`<br>`typesetter/</</<@bundle.js:34378:9`<br>`typesetter/</<@bundle.js:34377:14`<br>`compose/</<@bundle.js:33341:14`<br>`compose/<@bundle.js:33340:12`<br>`layout@bundle.js:33366:5`<br>`layoutText@bundle.js:25080:7`<br>`measureText@bundle.js:25095:7`<br>`./node_modules/yoga-layout-prebuilt/yoga-layout/dist/entry-common.js/module.exports/</<@bundle.js:99073:28`<br>`@bundle.js line 90296 > eval:1:86`<br>`./node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js/</</ASM_CONSTS<@bundle.js:89404:12`<br>`_emscripten_asm_const_iiididi@bundle.js:89412:28`<br>`Tg@bundle.js:92559:1`<br>`Rg@bundle.js:92555:1`<br>`Qg@bundle.js:92552:1`<br>`Pg@bundle.js:92546:1`<br>`we@bundle.js:92048:1`<br>`Yd@bundle.js:91902:1`<br>`Td@bundle.js:91511:1`<br>`He@bundle.js:92149:1`<br>`Yd@bundle.js:91633:1`<br>`Td@bundle.js:91511:1`<br>`He@bundle.js:92149:1`<br>`Yd@bundle.js:91633:1`<br>`Td@bundle.js:91511:1`<br>`He@bundle.js:92149:1`<br>`Yd@bundle.js:91633:1`<br>`Td@bundle.js:91511:1`<br>`He@bundle.js:92149:1`<br>`Yd@bundle.js:91633:1`<br>`Td@bundle.js:91511:1`<br>`He@bundle.js:92149:1`<br>`Yd@bundle.js:91633:1`<br>`Td@bundle.js:91511:1`<br>`He@bundle.js:92149:1`<br>`Yd@bundle.js:91633:1`<br>`Td@bundle.js:91511:1`<br>`He@bundle.js:92149:1`<br>`Yd@bundle.js:91633:1`<br>`Td@bundle.js:91511:1`<br>`_d@bundle.js:91922:1`<br>`kh@bundle.js:92608:1`<br>`qj@bundle.js:93134:1`<br>`oj@bundle.js:93126:1`<br>`XC@bundle.js:98755:1`<br>`makeMethodCaller/<@bundle.js:90329:57`<br>`./node_modules/yoga-layout-prebuilt/yoga-layout/dist/entry-common.js/module.exports/<@bundle.js:99086:12`<br>`./node_modules/yoga-layout-prebuilt/yoga-layout/dist/entry-common.js/module.exports/patch/prototype[name]@bundle.js:98985:14`<br>`calculateLayout@bundle.js:22572:5`<br>`_callee3$@bundle.js:24677:15`<br>`tryCatch@bundle.js:38363:37`<br>`invoke@bundle.js:38597:22`<br>`defineIteratorMethods/</prototype[method]@bundle.js:38415:16`<br>`step@bundle.js:37905:30`<br>`step/<@bundle.js:37916:13`<br>`run@bundle.js:49373:22`<br>`notify/<@bundle.js:49390:30`<br>`flush@bundle.js:47960:9` | `Error: Script terminated by timeout at:`<br>`positionAtIndex@bundle.js:35264:21`<br>`getGlyphWidth@bundle.js:35278:12`<br>`finalizeLineFragment/<@bundle.js:34277:28`<br>`layoutParagraph/</<@bundle.js:34345:7`<br>`layoutParagraph/<@bundle.js:34344:5`<br>`layoutContainer@bundle.js:34362:23`<br>`typesetter/</</<@bundle.js:34378:9`<br>`typesetter/</<@bundle.js:34377:14`<br>`compose/</<@bundle.js:33341:14`<br>`compose/<@bundle.js:33340:12`<br>`layout@bundle.js:33366:5`<br>`layoutText@bundle.js:25080:7`<br>`measureText@bundle.js:25095:7`<br>`./node_modules/yoga-layout/dist/entry-common.js/module.exports/</<@bundle.js:99073:28`<br>`@bundle.js line 90296 > eval:1:86`<br>`./node_modules/yoga-layout/build/Release/nbind.js/</</ASM_CONSTS<@bundle.js:89404:12`<br>`_emscripten_asm_const_iiididi@bundle.js:89412:28`<br>`Tg@bundle.js:92559:1`<br>`Rg@bundle.js:92555:1`<br>`Qg@bundle.js:92552:1`<br>`Pg@bundle.js:92546:1`<br>`we@bundle.js:92048:1`<br>`Yd@bundle.js:91902:1`<br>`Td@bundle.js:91511:1`<br>`He@bundle.js:92149:1`<br>`Yd@bundle.js:91633:1`<br>`Td@bundle.js:91511:1`<br>`He@bundle.js:92149:1`<br>`Yd@bundle.js:91633:1`<br>`Td@bundle.js:91511:1`<br>`He@bundle.js:92149:1`<br>`Yd@bundle.js:91633:1`<br>`Td@bundle.js:91511:1`<br>`He@bundle.js:92149:1`<br>`Yd@bundle.js:91633:1`<br>`Td@bundle.js:91511:1`<br>`He@bundle.js:92149:1`<br>`Yd@bundle.js:91633:1`<br>`Td@bundle.js:91511:1`<br>`He@bundle.js:92149:1`<br>`Yd@bundle.js:91633:1`<br>`Td@bundle.js:91511:1`<br>`He@bundle.js:92149:1`<br>`Yd@bundle.js:91633:1`<br>`Td@bundle.js:91511:1`<br>`_d@bundle.js:91922:1`<br>`kh@bundle.js:92608:1`<br>`qj@bundle.js:93134:1`<br>`oj@bundle.js:93126:1`<br>`XC@bundle.js:98755:1`<br>`makeMethodCaller/<@bundle.js:90329:57`<br>`./node_modules/yoga-layout/dist/entry-common.js/module.exports/<@bundle.js:99086:12`<br>`./node_modules/yoga-layout/dist/entry-common.js/module.exports/patch/prototype[name]@bundle.js:98985:14`<br>`calculateLayout@bundle.js:22572:5`<br>`_callee3$@bundle.js:24677:15`<br>`tryCatch@bundle.js:38363:37`<br>`invoke@bundle.js:38597:22`<br>`defineIteratorMethods/</prototype[method]@bundle.js:38415:16`<br>`step@bundle.js:37905:30`<br>`step/<@bundle.js:37916:13`<br>`run@bundle.js:49373:22`<br>`notify/<@bundle.js:49390:30`<br>`flush@bundle.js:47960:9`<br>`GlyphString.js:202` |

**Comment by DuncanMacWeb** [comment]
Ooh exciting! This appears to have been resolved by #474. You can test this by `npm i github:SDFE/react-pdf#474` :)

**Comment by v1adko** [comment]
Still seeing this in **1.6.13** both on Mac versions of Chrome (v89.0.4389.90), Firefox (86.0.1), and Safari (v14.0.2)
[CSB Link](https://codesandbox.io/s/broken-fire-0l53j?file=/src/App.tsx)
Disabling loop protection does not render the Document within PDFViewer

Needed this to attempt to reproduce another possible issue I've encountered.
Anyone can suggest an alternative environment to CodeSandbox for this purpose?
