### ISSUE TITLE
PDFDownloadLink Issue

### ISSUE THREAD

**Issue by exneval** [diegomura/react-pdf#855]
**Describe the bug**
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in InternalBlobProvider (created by PDFDownloadLink)
    in PDFDownloadLink (at user.js:182)

**To Reproduce**
Just use the component PDFDownloadLink with normal setup.
If the we try to load the page that have the PDFDownloadLink for **second time only**, the warning appears.

**Expected behavior**
No warning

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Opera]
 - React-pdf version [1.6.8]

**Comment by geerthoekzema** [comment]
This is an known issue, see #420 
Rerendering of the (already) rendered PDF element will cause an error.

To solve this issue, I've created an element with a button in it. When the user clicks the button the PDF render button appears. When the users leaves the view, and returns. My own component shows and the PDF render button is discarded.

**Comment by exneval** [comment]
`<PDFDownloadLink
                document={
                  <StudentDoc />
                }
                fileName={`${getFullName(firstName, lastName)
                  .trim()
                  .replace(/ /g, "_")}.pdf`}
              >
                {({ blob, url, loading, error }) => (
                  <Button
                    className="student-btn"
                    size="large"
                    disabled={loading}
                  >
                    {loading ? "Loading ..." : "Download CV"}
                  </Button>
                )}
              </PDFDownloadLink>`

@geerthoekzema this is how I've implemented the component, wdyt? Thanks for your respond

**Comment by tafelito** [comment]
same issue happens after saving any changes using Fast Refresh, even when having just one instance of the `PDFDownloadLink`. `PDFDownloadLink` is probably missing a cleanup function when unmounting as the error clearly says. I will try to create a PRD to fix it if I can

**Comment by diegomura** [comment]
Fixed in 2.0

**Comment by Katedam** [comment]
I'm still seeing this exact issue and I'm using version 2.0.15
OS: iOS
Browser: Chrome

**Comment by seanemmer** [comment]
Also Experiencing this issue

OS: Mac OS
Browser: Firefox
